baseURL = "https://multer.com/"
locale = "en-us"
title = "Multer family website"
theme = "PaperMod"
mainSections = ["posts"]

[taxonomies]
tag = "tags"
author = "authors"

[[menus.main]]
name = "Home"
pageRef = "/"
weight = 10

[[menus.main]]
name = "Posts"
pageRef = "/posts/"
weight = 20

[[menus.main]]
name = "People"
pageRef = "/people/"
weight = 30

[[menus.main]]
name = "About"
pageRef = "/about/"
weight = 40

[caches.images]
dir = ":cacheDir/images"
