baseURL = "http://localhost:1313/"
locale = "en-us"
title = "Multer family website"
theme = "PaperMod"
mainSections = ["posts"]

[taxonomies]
tag = "tags"
author = "authors"

[outputs]
home = ["HTML", "RSS", "JSON"]

[[menus.main]]
name = "Home"
pageRef = "/"
weight = 10

[[menus.main]]
name = "Posts"
pageRef = "/posts/"
weight = 20

[[menus.main]]
name = "People"
pageRef = "/people/"
weight = 30

[[menus.main]]
name = "About"
pageRef = "/about/"
weight = 40

[[menus.main]]
name = "Search"
pageRef = "/search/"
weight = 50

[caches.images]
dir = ":cacheDir/images"
